#!/usr/bin/env python
# _*_ coding: cp1252 _*_
# _*_ cdoing: 850 _*_
# _*_ coding: utf-8 _*_
autos=['VOLKSWAGEN', 'AUDI', 'PEUGEOT', 'MERCEDEZ', 'NISSAN', 'BMW', 'SUBARU'] #Declaramos una lista de marcas de carro
autos.append('TOYOTA')#Con la funcion append agregamos toyota al final de la lista
autos.insert(0,"FERRARI")#Con la funcion insert escogemos agregar ferrari en la posicion 0 de la lista
print(autos)#imprimimos la lista actualizada