#Cambia el operador para que la condición sea True.
num1 = 15 #DECLARAMOS UN NUMERO
num2 = 20 #DECLARAMOS UN NUMERO

if num1 < num2: #SI NUMERO 1 ES MENOR A NUMERO 2 SE EJECUTA ESTE IF
	print('Se ejecuta el if.')
	
#Cambia el operador para que la condición sea True.

num1 = 1450  #DECLARAMOS UN NUMERO
num2 = 60 #DECLARAMOS UN NUMERO

if num1 > num2: #SI NUMERO 1 ES MAYOR A NUMERO 2 SE EJECUTA ESTE IF
	print('Se ejecuta el if.')

#Haz que el siguiente condicional se convierta en False sin cambiar el operador

num1 = 1450 #DECLARAMOS UN NUMERO
num2 = 60  #DECLARAMOS UN NUMERO

if num1 == num2: #SI NUMERO 1 ES IGUAL A NUMERO 2 SE EJECUTA ESTE IF
	print('Se ejecuta el if.')