#!/usr/bin/env python
# _*_ coding: cp1252 _*_
# _*_ cdoing: 850 _*_
# _*_ coding: utf-8 _*_

Nombre="anTonIo lopEz" #declaramos variable
Escuela="CETI" #declaramos variable
Materia="INteligENcia aRtIficiAl" #declaramos variable
print(Nombre.upper(),'\n') #aplicamos upper para el nombre
print(Escuela.lower() ,'\n') #aplicamos lower para escuela
print( Materia.title()) #aplicamos title para materia
print("\nLista de LENGUAJES\n\tPython\n\tC++ " ) #hacemos una demostracion de tabulaciones y saltos de linea