#!/usr/bin/env python
# _*_ coding: cp1252 _*_
# _*_ cdoing: 850 _*_
# _*_ coding: utf-8 _*_

suma=20+23+45 #declaramos una suma
resta=20-23-45 #declaramos una resta
multiplicacion=31*2*6 #declaramos una multiplicacion
division=100/25 #declaramos una division
operacion=((10-5)*15)/17 #declaramos una operacion cualquiera
exponencial=2**3 #declaramos una exponencial
print( ' ',suma,'\n',resta,'\n',multiplicacion,'\n',division)#imprimimos todas las operaciones
print( ' ',operacion)#imprimimos la operacion
print( ' ',exponencial)#imprimimos la exponencial